version: '3'
services:
  node:
    image: node:8.7.0-alpine
    working_dir: /code/api
    volumes:
      - ".:/code/api"
    command: sh -c 'yarn install && yarn dev'
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:3.4.1
    working_dir: /opt/mongodb
    volumes:
      - mongodb_data:/opt/mongodb
    command: sh -c 'mkdir -p /opt/mongodb && mongod --port 27017 --dbpath /opt/mongodb'
    ports:
      - "3001:27017"

volumes:
  mongodb_data:
